# Default values for auth.
# This is a YAML-formatted file.
#do not change, no support for multiple instances
replicaCount: 1 

image:
  repository: overv/openstreetmap-tile-server
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80

osm:
  automaticUpdates: true
  data:
    download: true
#    pbfUrl: "https://download.geofabrik.de/europe/great-britain-latest.osm.pbf"
#    polyUrl: "https://download.geofabrik.de/europe/great-britain.poly"  
    pbfUrl: "https://download.geofabrik.de/europe/great-britain/england/northamptonshire-latest.osm.pbf"
    polyUrl: "https://download.geofabrik.de/europe/great-britain/england/northamptonshire.poly"  
  storage:
    dataSize: 10Gi
    tileSize: 10Gi

#resources: 
#  limits: 
#    memory: "150M"
#  requests:
#    memory: "75M"    
#nodeSelector: {}
#tolerations: []
#affinity: {}