apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "osmts.fullname" . }}-tilespvc  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.osm.storage.tileSize }}